#!/bin/bash
# this script convert a pdf to its json format with metadata
# $1 is the input PDF file
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"/
cat $1 | python ${SCRIPT_DIR}pdfmeta/addmeta.py
